
# TODO: Function to send a content to the user
# Initial functionality will be to use the console to emulate communicating with SMS


# test the content bot


# TODO: Function to add their response to the database


# TODO: Get a list of questions to ask the user based on the kind of job they want to apply for


# TODO: Feed the responses to the questions, and user's name and contact information to Chat GPT to generate a resume


# TODO: Save the resume generated by Chat GPT as a pdf


# TODO: create a link to the PDF resume for the user to look at it


# TODO: Get feedback from the user about the quality of the resume and feed it back to Chat GPT and get a revised version


# TODO: Collect the user's Name, and contact information for the resume
